### ISSUE TITLE
Play/Pause not working

### ISSUE THREAD

**Issue by KE55ARD** [cdnninja/yoto_ha#35]
I just managed to muddle my way through installing this integration and I'm SO thankful you made it!

Sadly the one thing I wanted it for is the one thing not working, play/pause.

I have a full sized Yoto player (3rd gen I believe). Logging in and adding the device all worked perfectly and I see a bunch of sensors reporting correctly.

And side note, can play & pause be used separately? So you know you are pausing somehow?

Thanks!

**Comment by cdnninja** [comment]
Your right looks like I have a bug in that.  I have been working on play pause last day or two. My underlying api works though so I should be able to get this fixed shortly.

**Comment by cdnninja** [comment]
Okay should be fixed now.  I also encourage you to install this via HACS so that you get prompted for auto updates.  I have added a bit to the readme on this.  

Play / pause works separately after the update comes in. Currently that only comes every 30 minutes.  On my to do list is to fix that here: https://github.com/cdnninja/yoto_ha/issues/31

If you go to the developer menu and run the yoto update
![image](https://github.com/cdnninja/yoto_ha/assets/6373468/1f703486-ab54-4001-9065-bc8c3c295e14)

It will force it to update, not good practice but shows what it should look like without waiting 30 minutes.  I plan to work on dialing in data update speed now since I think that is important for this to be useful.

**Comment by KE55ARD** [comment]
Oh amazing thanks, working through that readme now!

To be fair I'm pretty sure I tried the steps you've described and it didn't "find" it before. So not sure what's different now :/

**Comment by KE55ARD** [comment]
Ok installed via HACS, worked fine pasting in the github link this time.

Re-added the integration and signed in all fine, but yet the play/pause button still isn't triggering...

**Comment by KE55ARD** [comment]
Oh the play/pause wasn't working in the actual device page, but calling the service "pause" does! :D

**Comment by cdnninja** [comment]
Right now the button starts as play pause.   After it scans and sees it's currently playing it switches to a pause button that works.  

Home assistant just doesn't know the status on startup.  Once I fix real time updates that will go away.

**Comment by cdnninja** [comment]
Closing as real time display is tracked in #31

**Comment by cdnninja** [comment]
Real time updates are working now so play pause feels responsive now.  Only master branch not a release just yet.
